import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import { Query } from "@tanstack/react-query";
import { QueryProvider } from "@/provider/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
  icons:{
    icon:'/logo1.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider>
       <html lang="en">
      <body className={inter.className}>
      <QueryProvider>
        {children}
        </QueryProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
